
GET http://localhost:3000/api/cars HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/api/users/5d37d64e47033213800078d7 HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
  "firstname": "midnight",
  "lastname": "speller",
  "email": "midnight.speller@gmail.com"
}

###

PUT http://localhost:3000/api/users/5d37d64e47033213800078d7 HTTP/1.1
Content-Type: application/json

{
  "firstname": "aj",
  "lastname": "speller",
  "email": "aj.speller@gmail.com"
}

###

PATCH http://localhost:3000/api/users/5d37d64e47033213800078d7 HTTP/1.1
Content-Type: application/json

{
  "firstname": "aj"
}

###

DELETE http://localhost:3000/api/users/5d37d64e47033213800078d7 HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/api/users/5d37d64e47033213800078d7/cars HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3000/api/users/5d37d64e47033213800078d7/cars HTTP/1.1
Content-Type: application/json

{
  "make": "Chevy",
  "model": "Volt",
  "year": 2007
}

###
POST http://localhost:3000/api/cars
Content-Type: application/json

{
  "seller": "5d37d64e47033213800078d7",
  "make": "BMW",
  "model": "745",
  "year": 2018
}

###

GET http://localhost:3000/api/cars/5d3e6ee4c77f307ce62c59c9 HTTP/1.1
Content-Type: application/json

###

PUT http://localhost:3000/api/cars/5d3e6ee4c77f307ce62c59c9 HTTP/1.1
Content-Type: application/json

{
  "make": "Toyota",
  "model": "Prius",
  "year": 2099
}

###

PATCH http://localhost:3000/api/cars/5d3e6ee4c77f307ce62c59c9 HTTP/1.1
Content-Type: application/json

{
  "make": "Toyota",
  "model": "Prius",
  "year": 2099
}

DELETE http://localhost:3000/api/cars/5d3e6ee4c77f307ce62c59c9 HTTP/1.1
Content-Type: application/json
