
GET http://localhost:3000/api/cars HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/api/users/5d37d64e47033213800078d7 HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
  "firstname": "alfred",
  "lastname": "speller",
  "email": "ajs@gmail.com"
}

###